CREATE FUNCTION `mm_agentBelongs`(
  id BIGINT, superior BIGINT
)
  RETURNS SMALLINT DETERMINISTIC COMMENT 'id 从属于或者间接从属于 superior 则1' BEGIN DECLARE result SMALLINT;
  SELECT
    superior IN (t0.`ID`, t1.`ID`, t2.`ID`, t3.`ID`, t4.`ID`, t5.`ID`, t6.`ID`, t7.`ID`, t8.`ID`, t9.`ID`, t10.`ID`)
  INTO result
  FROM `AGENTLEVEL` AS t0 LEFT JOIN `AGENTLEVEL` AS t1 ON t0.`SUPERIOR_ID` = t1.`ID`
    LEFT JOIN `AGENTLEVEL` AS t2 ON t1.`SUPERIOR_ID` = t2.`ID`
    LEFT JOIN `AGENTLEVEL` AS t3 ON t2.`SUPERIOR_ID` = t3.`ID`
    LEFT JOIN `AGENTLEVEL` AS t4 ON t3.`SUPERIOR_ID` = t4.`ID`
    LEFT JOIN `AGENTLEVEL` AS t5 ON t4.`SUPERIOR_ID` = t5.`ID`
    LEFT JOIN `AGENTLEVEL` AS t6 ON t5.`SUPERIOR_ID` = t6.`ID`
    LEFT JOIN `AGENTLEVEL` AS t7 ON t6.`SUPERIOR_ID` = t7.`ID`
    LEFT JOIN `AGENTLEVEL` AS t8 ON t7.`SUPERIOR_ID` = t8.`ID`
    LEFT JOIN `AGENTLEVEL` AS t9 ON t8.`SUPERIOR_ID` = t9.`ID`
    LEFT JOIN `AGENTLEVEL` AS t10 ON t9.`SUPERIOR_ID` = t10.`ID`
  WHERE t0.`ID` = id;
  RETURN result;
END